on:
  release:
    types: [created]
name: Release
jobs:
  linux:
    name: Release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: release linux/amd64
      uses: wangyoucao577/go-release-action@v1.17
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: linux
        CGO_ENABLED: 0
  windows:
    name: Release windows/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: release windows/amd64
      uses: wangyoucao577/go-release-action@v1.17
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: windows
  darwin:
    name: Release darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: release darwin/amd64
      uses: wangyoucao577/go-release-action@v1.17
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: darwin
